# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ActiveStorage::AnalyzeJob.queue_adapter = :inline
ActiveStorage::PurgeJob.queue_adapter = :inline

Admin.create!(
  [
    {email: 'admin@test.com', password: 'admintest'}
  ]
)

end_users = EndUser.create!(
  [
    {email: 'test@test.com', name: 'tester', password: 'testtest', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/no_image.jpg"), filename:"no_image.jpg")},
    {email: 'man1@test.com', name: 'マーシー', password: 'testman1', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man1.jpg"), filename:"man1.jpg")},
    {email: 'man2@test.com', name: '小柳 久作', password: 'testman2', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man2.jpg"), filename:"man2.jpg")},
    {email: 'man3@test.com', name: 'てる', password: 'testman3', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man3.jpg"), filename:"man3.jpg")},
    {email: 'man4@test.com', name: '小出 佐十郎', password: 'testman4', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man4.jpg"), filename:"man4.jpg")},
    {email: 'man5@test.com', name: 'グレイテストショーイチ', password: 'testman5', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man5.jpg"), filename:"man5.jpg")},
    {email: 'man6@test.com', name: '青柳', password: 'testman6', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man6.jpg"), filename:"man6.jpg")},
    {email: 'man7@test.com', name: '幸博', password: 'testman7', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man7.jpg"), filename:"man7.jpg")},
    {email: 'man8@test.com', name: 'まっすう', password: 'testman8', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man8.jpg"), filename:"man8.jpg")},
    {email: 'man9@test.com', name: 'たばた', password: 'testman9', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man9.jpg"), filename:"man9.jpg")},
    {email: 'man10@test.com', name: 'うえだこー', password: 'testman10', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man10.jpg"), filename:"man10.jpg")},
    {email: 'man11@test.com', name: 'いまい　いまいち', password: 'testman11', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man11.jpg"), filename:"man11.jpg")},
    {email: 'man12@test.com', name: 'やまなかこうじ', password: 'testman12', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man12.jpg"), filename:"man12.jpg")},
    {email: 'man13@test.com', name: '高山 元信', password: 'testman13', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/man13.jpg"), filename:"man13.jpg")},
    {email: 'woman1@test.com', name: 'レイ', password: 'testwoman1', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman1.jpg"), filename:"woman1.jpg")},
    {email: 'woman2@test.com', name: '中田 玲', password: 'testwoman2', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman2.jpg"), filename:"woman2.jpg")},
    {email: 'woman3@test.com', name: 'ジュンジュリ', password: 'testwoman3', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman3.jpg"), filename:"woman3.jpg")},
    {email: 'woman4@test.com', name: 'えーちゃん', password: 'testwoman4', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman4.jpg"), filename:"woman4.jpg")},
    {email: 'woman5@test.com', name: '咲子', password: 'testwoman5', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman5.jpg"), filename:"woman5.jpg")},
    {email: 'woman6@test.com', name: '西川 章子', password: 'testwoman6', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman6.jpg"), filename:"woman6.jpg")},
    {email: 'woman7@test.com', name: 'つっちーさん', password: 'testwoman7', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman7.jpg"), filename:"woman7.jpg")},
    {email: 'woman8@test.com', name: 'るりるり', password: 'testwoman8', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman8.jpg"), filename:"woman8.jpg")},
    {email: 'woman9@test.com', name: 'がんこっこ', password: 'testwoman9', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman9.jpg"), filename:"woman9.jpg")},
    {email: 'woman10@test.com', name: 'クリスティーナ', password: 'testwoman10', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman10.jpg"), filename:"woman10.jpg")},
    {email: 'woman11@test.com', name: '東 順子', password: 'testwoman11', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman11.jpg"), filename:"woman11.jpg")},
    {email: 'woman12@test.com', name: 'アドミニストれーこ', password: 'testwoman12', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman12.jpg"), filename:"woman12.jpg")},
    {email: 'woman13@test.com', name: 'ゆうこはん', password: 'testwoman12', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/woman13.jpg"), filename:"woman13.jpg")},
    {email: 'manbaby@test.com', name: 'ゆうた', password: 'testmanbaby', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/manbaby.jpg"), filename:"manbaby.jpg")},
    {email: 'mancouple@test.com', name: 'パパおさん', password: 'testmancouple', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/mancouple.jpg"), filename:"mancouple.jpg")},
    {email: 'womancouple@test.com', name: 'ママこさん', password: 'testwomancouple', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/womancouple.jpg"), filename:"womancouple.jpg")}
  ]
)

groups = Group.create!(
  [
    {name: 'testgroup', introduction: 'testgroupintroduction', owner_id: end_users[1].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/no_image.jpg"), filename:"no_image.jpg")},
    {name: '祭だ！祭だ！！わっしょい！！', introduction: '祭が好きな人や、祭娘が好きな人達で交流しましょう！絶賛メンバー募集中です！', owner_id: end_users[7].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.matsuri.matsurimusume.jpg"), filename:"group.matsuri.matsurimusume.jpg")},
    {name: 'スポーツ好き集まれ！！', introduction: 'スポーツなら何でもOK！！みんなのスポーツをおしえて！！そしてお互いに高め合いましょう！！', owner_id: end_users[13].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.sports.roadbike.jpg"), filename:"group.sports.roadbike.jpg")},
    {name: 'だらだら過ごす時間の共有場所', introduction: 'だらだらしているときに、みんなのだらだらを共有しよう！そして一緒にだらだらしましょう！だ～らだら～。', owner_id: end_users[21].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.daradara.catonpc.jpg"), filename:"group.daradara.catonpc.jpg")},
    {name: 'チーム食べる前に自慢', introduction: '美味しいものや自分で作った料理など、みんなで自慢し合いましょう！', owner_id: end_users[23].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.kaisendon.jpg"), filename:"group.eat.kaisendon.jpg")},
    {name: 'みんなの会社の楽しい写真！！！', introduction: 'みんなの会社の楽しかった思い出を共有しようぜ！', owner_id: end_users[10].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.kaisya.ofuzake.jpg"), filename:"group.kaisya.ofuzake.jpg")},
    {name: 'うちのカレカノが最高だ！', introduction: '彼女のかわいいところや、彼氏のカッコいいところ、好きなところなど、みんなに共有してもっと好きになろう！！誹謗中傷は絶対やめてください。', owner_id: end_users[2].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.karekano.nomukanojo.jpg"), filename:"group.karekano.nomukanojo.jpg")},
    {name: '今井一家団らん', introduction: '今井一家のグループです。今井一家の人のみ加入許可します。', owner_id: end_users[29].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.dog.jpg"), filename:"group.family.dog.jpg")},
    {name: 'まっすう用', introduction: '個人利用', owner_id: end_users[8].id, group_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.kozinriyou.vrsamurai.jpg"), filename:"group.kozinriyou.vrsamurai.jpg")}
  ]
)

GroupUser.create!(
  [
    {group_id: groups[1].id, end_user_id: end_users[7].id},
    {group_id: groups[1].id, end_user_id: end_users[11].id},
    {group_id: groups[1].id, end_user_id: end_users[14].id},
    {group_id: groups[1].id, end_user_id: end_users[16].id},
    {group_id: groups[1].id, end_user_id: end_users[18].id},
    {group_id: groups[1].id, end_user_id: end_users[19].id},
    {group_id: groups[1].id, end_user_id: end_users[22].id},
    {group_id: groups[1].id, end_user_id: end_users[26].id},
    {group_id: groups[2].id, end_user_id: end_users[13].id},
    {group_id: groups[2].id, end_user_id: end_users[12].id},
    {group_id: groups[2].id, end_user_id: end_users[20].id},
    {group_id: groups[2].id, end_user_id: end_users[7].id},
    {group_id: groups[2].id, end_user_id: end_users[6].id},
    {group_id: groups[2].id, end_user_id: end_users[4].id},
    {group_id: groups[2].id, end_user_id: end_users[15].id},
    {group_id: groups[2].id, end_user_id: end_users[9].id},
    {group_id: groups[2].id, end_user_id: end_users[23].id},
    {group_id: groups[2].id, end_user_id: end_users[25].id},
    {group_id: groups[3].id, end_user_id: end_users[21].id},
    {group_id: groups[3].id, end_user_id: end_users[10].id},
    {group_id: groups[3].id, end_user_id: end_users[17].id},
    {group_id: groups[3].id, end_user_id: end_users[24].id},
    {group_id: groups[4].id, end_user_id: end_users[23].id},
    {group_id: groups[4].id, end_user_id: end_users[11].id},
    {group_id: groups[4].id, end_user_id: end_users[22].id},
    {group_id: groups[4].id, end_user_id: end_users[1].id},
    {group_id: groups[4].id, end_user_id: end_users[4].id},
    {group_id: groups[4].id, end_user_id: end_users[7].id},
    {group_id: groups[4].id, end_user_id: end_users[9].id},
    {group_id: groups[4].id, end_user_id: end_users[20].id},
    {group_id: groups[4].id, end_user_id: end_users[12].id},
    {group_id: groups[4].id, end_user_id: end_users[16].id},
    {group_id: groups[5].id, end_user_id: end_users[10].id},
    {group_id: groups[5].id, end_user_id: end_users[15].id},
    {group_id: groups[5].id, end_user_id: end_users[18].id},
    {group_id: groups[6].id, end_user_id: end_users[2].id},
    {group_id: groups[6].id, end_user_id: end_users[20].id},
    {group_id: groups[6].id, end_user_id: end_users[28].id},
    {group_id: groups[6].id, end_user_id: end_users[29].id},
    {group_id: groups[6].id, end_user_id: end_users[3].id},
    {group_id: groups[6].id, end_user_id: end_users[11].id},
    {group_id: groups[7].id, end_user_id: end_users[29].id},
    {group_id: groups[7].id, end_user_id: end_users[28].id},
    {group_id: groups[7].id, end_user_id: end_users[27].id},
    {group_id: groups[7].id, end_user_id: end_users[17].id},
    {group_id: groups[7].id, end_user_id: end_users[11].id},
    {group_id: groups[8].id, end_user_id: end_users[8].id},
  ]
)

GroupMemory.create!(
  [
    {title: '素敵な浴衣姿', memo: '姉です！素敵だったので撮ってたのですが、せっかくなので皆さんに見せたいと思いました！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.matsuri.yukata.jpg"), filename:"group.matsuri.yukata.jpg"), end_user_id: end_users[7].id, group_id: groups[1].id },
    {title: '気合の入った祭娘', memo: '家族です。実は家族みんなで祭り好きです。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.matsuri.matsurimusume.jpg"), filename:"group.matsuri.matsurimusume.jpg"), end_user_id: end_users[26].id, group_id: groups[1].id },
    {title: '可愛い娘', memo: 'うちの娘です。とってもかわいくてみんなに共有したくなりました。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.matsuri.musumeyukata.jpg"), filename:"group.matsuri.musumeyukata.jpg"), end_user_id: end_users[19].id, group_id: groups[1].id },
    {title: 'サイクリング！', memo: '友達とサイクリングしてきました！！最高に気持ち良かったです！友達のロードバイクはとっても買えないです！((高い)', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.sports.roadbike.jpg"), filename:"group.sports.roadbike.jpg"), end_user_id: end_users[7].id, group_id: groups[2].id },
    {title: '蹴ったふり', memo: '友達がサッカーの元日本代表で久しぶりに会ったときにやってもらいました。(笑)すごくないですか？', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.sports.kerikaburi.jpg"), filename:"group.sports.kerikaburi.jpg"), end_user_id: end_users[25].id, group_id: groups[2].id },
    {title: 'ランニングの休憩したときの写真', memo: '友達です。自分は恥ずかしいので映っていませんが、友達よりは写真を取るくらいにはまだ元気がありました！いえい。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.sports.kyuukei.jpg"), filename:"group.sports.kyuukei.jpg"), end_user_id: end_users[23].id, group_id: groups[2].id },
    {title: '限界を迎えた友', memo: 'その友達が、普段からは想像できないくらい、頑張って走っていたのでとても感動しました！でも、ちょっとおもしろい感じになっちゃったです。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.sports.runninggenkai.jpg"), filename:"group.sports.runninggenkai.jpg"), end_user_id: end_users[4].id, group_id: groups[2].id },
    {title: '弟のだらだら', memo: '弟のだらだらが本当に素晴らしいほどだらだらだったので共有します。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.daradara.bedsumaho.jpg"), filename:"group.daradara.bedsumaho.jpg"), end_user_id: end_users[21].id, group_id: groups[3].id },
    {title: '結果的にだらだら', memo: '私はだらだらしてなかったのですが、うちのにゃんこが来ちゃいました。(笑)結果的には私もだらだらしてしました。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.daradara.catonpc.jpg"), filename:"group.daradara.catonpc.jpg"), end_user_id: end_users[12].id, group_id: groups[3].id },
    {title: '美味しすぎるカレー', memo: '見てわかる通り、スパイシーなカレーなのですが、美味しすぎました。お店がxx県のxx市xxにあるのでぜひ皆さんもどうぞ！！店名：カレーどころかれえどう', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.cary.jpg"), filename:"group.eat.cary.jpg"), end_user_id: end_users[23].id, group_id: groups[4].id },
    {title: 'チャーハン作ってみました。', memo: 'いつもより本格的なチャーハンを作ってみました。とてもおいしくできました。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.chahan.jpg"), filename:"group.eat.chahan.jpg"), end_user_id: end_users[23].id, group_id: groups[4].id },
    {title: 'いくら多めの海鮮丼！！', memo: 'プチプチ触感の最高な海鮮丼！！自分はいくらが大好きなので、めちゃめちゃ嬉しかったです！！店名：いくらはいくらだい？', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.kaisendon.jpg"), filename:"group.eat.kaisendon.jpg"), end_user_id: end_users[11].id, group_id: groups[4].id },
    {title: '母さんの味噌汁', memo: 'うちの母さんの味噌汁が世界一旨いし、映える映える。店名：無し(うちの母のだからね！笑)', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.misosoup.jpg"), filename:"group.eat.misosoup.jpg"), end_user_id: end_users[1].id, group_id: groups[4].id },
    {title: '大盛り太郎系ラーメン！！', memo: 'さすがの自分も結構お腹いっぱいになりましたが、最後までおいしく食べれました。お薦めです。店名：ちょうでからめんまん', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.ramen.jpg"), filename:"group.eat.ramen.jpg"), end_user_id: end_users[9].id, group_id: groups[4].id },
    {title: '初めて食べた汁なし担々麵', memo: '汁なし担々麵初めてだったけど、こんなにおいしいんですね！まだ食べたことない人は一度食べてほしいです！店名：汁なしめん処ノンスープ', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.shirunashitantanmen.jpg"), filename:"group.eat.shirunashitantanmen.jpg"), end_user_id: end_users[23].id, group_id: groups[4].id },
    {title: '水餃子', memo: '水餃子っておいしいんですね！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.suigyouza.jpg"), filename:"group.eat.suigyouza.jpg"), end_user_id: end_users[12].id, group_id: groups[4].id },
    {title: '知り合いの料理屋の厨房で撮った写真', memo: 'この人物が知り合いです。ここの店は本当に全メニューがおいしいです。ぜひ！店名：厨房おじさん', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.eat.tyuubou.jpg"), filename:"group.eat.tyuubou.jpg"), end_user_id: end_users[20].id, group_id: groups[4].id },
    {title: '社長が本当に面白いんです！', memo: 'この人社長です！笑。このくらいはっちゃけた社長って珍しくないですか？本当にこの会社に入れて嬉しいです。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.kaisya.ofuzake.jpg"), filename:"group.kaisya.ofuzake.jpg"), end_user_id: end_users[10].id, group_id: groups[5].id },
    {title: '少し怒っている上司がカッコいい', memo: '怒れせてしまったのですが、そんな上司の姿がカッコよすぎるのです。反省しなくちゃいけないのは分かっています。でも、カッコええ～。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.kaisya.jhoushi.jpg"), filename:"group.kaisya.jhoushi.jpg"), end_user_id: end_users[15].id, group_id: groups[5].id },
    {title: 'プレゼン前のリハーサルが本気', memo: 'リハーサルですよこれ。おもしろすぎません？本当にこの人が好きです(笑)', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.kaisya.purezen.jpg"), filename:"group.kaisya.purezen.jpg"), end_user_id: end_users[18].id, group_id: groups[5].id },
    {title: '彼女が可愛すぎる！', memo: 'じゃじゃーんてやってる。いかがですか？', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.karekano.jajaan.jpg"), filename:"group.karekano.jajaan.jpg"), end_user_id: end_users[2].id, group_id: groups[6].id },
    {title: 'おかえり！！', memo: '待ってたよ！こんな時期だから仕方ないけど、2年も待った。本当にうれしいんだ！！！！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.karekano.kikoku.jpg"), filename:"group.karekano.kikoku.jpg"), end_user_id: end_users[3].id, group_id: groups[6].id },
    {title: '美しすぎる私のパートナー', memo: 'この子は私のものです。皆さんにはあげませんよ？(笑)', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.karekano.nomukanojo.jpg"), filename:"group.karekano.nomukanojo.jpg"), end_user_id: end_users[20].id, group_id: groups[6].id },
    {title: 'もじゃ助がかっけ～笑wwww', memo: '兄貴がもじゃ助にサングラス掛けて座らせてた。wwwww', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.dog.jpg"), filename:"group.family.dog.jpg"), end_user_id: end_users[29].id, group_id: groups[7].id },
    {title: 'おじいちゃんバックうまい', memo: 'さすが高齢でもまだまだ現役ですな！！いつまでも元気でいてね！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.carback.jpg"), filename:"group.family.carback.jpg"), end_user_id: end_users[28].id, group_id: groups[7].id },
    {title: '妻の脱毛器を使っている姿が美しすぎる', memo: '怒られちゃうかな(笑)', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.datsumouki.jpg"), filename:"group.family.datsumouki.jpg"), end_user_id: end_users[28].id, group_id: groups[7].id },
    {title: '娘を公園に連れて行ったぞ', memo: 'とても大きい遊具があった。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.dekaisuberidai.jpg"), filename:"group.family.dekaisuberidai.jpg"), end_user_id: end_users[11].id, group_id: groups[7].id },
    {title: '久々に兄弟とゲーセン行った。', memo: '白熱した～。また行きたい。ママこさんいい？わら', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.game.jpg"), filename:"group.family.game.jpg"), end_user_id: end_users[28].id, group_id: groups[7].id },
    {title: 'お兄ちゃんがだせえわら', memo: '似合わん！！わら', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.gentsuki.jpg"), filename:"group.family.gentsuki.jpg"), end_user_id: end_users[29].id, group_id: groups[7].id },
    {title: '娘の結婚式', memo: '', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.hag.jpg"), filename:"group.family.hag.jpg"), end_user_id: end_users[11].id, group_id: groups[7].id },
    {title: '孫がまた増える', memo: 'お金ならあるから安心せい。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.matanity.jpg"), filename:"group.family.matanity.jpg"), end_user_id: end_users[11].id, group_id: groups[7].id },
    {title: 'いとこの家', memo: 'この表所がたまらなく好きですわ！わら', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.odoroki.jpg"), filename:"group.family.odoroki.jpg"), end_user_id: end_users[28].id, group_id: groups[7].id },
    {title: 'きれい好きにも程がある(笑)', memo: 'この家、たててから4年だよ？キレイ過ぎない？わら。てか、色味なすぎやろ！！わら', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.family.souji.jpg"), filename:"group.family.souji.jpg"), end_user_id: end_users[29].id, group_id: groups[7].id },
    {title: 'VRx220を試用', memo: 'なかなか楽しかった。購入検討。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/group.kozinriyou.vrsamurai.jpg"), filename:"group.kozinriyou.vrsamurai.jpg"), end_user_id: end_users[8].id, group_id: groups[8].id },
  ]
)

memories = Memory.create!(
  [
    {title: 'testmemory', memo: 'testmemorymemo', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/no_image.jpg"), filename:"no_image.jpg"), end_user_id: end_users[1].id },
    {title: 'あ・か・べ・こ', memo: 'これ僕が作りました。どうですか？良かったらいいねしてね！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.akabeko.jpg"), filename:"image.akabeko.jpg"), end_user_id: end_users[2].id },
    {title: '青い花', memo: 'よく知らない花だけど、素敵でした。なんていう花なんでしょう。教えてください。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.aoihana.jpg"), filename:"image.aoihana.jpg"), end_user_id: end_users[2].id },
    {title: 'めっちゃ痛いけど、', memo: '痛いけど、きもち～！！らしいです。彼女の足です。わら', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.ashitsubo.jpg"), filename:"image.ashitsubo.jpg"), end_user_id: end_users[3].id },
    {title: 'こんな場所でも素敵な写真が撮れますよ。', memo: 'こういう隠れスポットがあるんですよ。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.birunosukima.jpg"), filename:"image.birunosukima.jpg"), end_user_id: end_users[4].id },
    {title: 'もうすぐですね！', memo: '今年はどうなるかな～。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.christmas.jpg"), filename:"image.christmas.jpg"), end_user_id: end_users[5].id },
    {title: '中華の龍がいいですね', memo: '私の好みです。このような模様を見ると興奮します。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.chuukamoyou.jpg"), filename:"image.chuukamoyou.jpg"), end_user_id: end_users[6].id },
    {title: '最高の夜', memo: '自分の人生でこんなことができるなんて想像もできなかったよ。ありがと。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.couplekanpai.jpg"), filename:"image.couplekanpai.jpg"), end_user_id: end_users[7].id },
    {title: 'ここが厄介', memo: 'ここが厄介なんですよ。知らんけど。誰か教えて～！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.cpu.jpg"), filename:"image.cpu.jpg"), end_user_id: end_users[7].id },
    {title: 'いい感じに撮れた！！', memo: 'イヤホンです。これ、3年使ってます。長持ちってレベルじゃないくらいキレイに使っています。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.earphone.jpg"), filename:"image.earphone.jpg"), end_user_id: end_users[8].id },
    {title: 'ロール系あるある', memo: '使い切らずに新しいもの出す。無限ループ。こうなる。わら', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.gamutepe.jpg"), filename:"image.gamutepe.jpg"), end_user_id: end_users[8].id },
    {title: 'ガラス玉', memo: '素敵でしょう。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.garasudama.jpg"), filename:"image.garasudama.jpg"), end_user_id: end_users[9].id },
    {title: 'ギターコレクション', memo: 'これ全てミーのでっせ。ただの自慢ですが、すごいって言ってほしい。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.guitar.jpg"), filename:"image.guitar.jpg"), end_user_id: end_users[9].id },
    {title: 'ファイアーフラワー', memo: 'スペシャルなデーになったです。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.hanabi.jpg"), filename:"image.hanabi.jpg"), end_user_id: end_users[10].id },
    {title: '鳩の家族', memo: '夫婦かな、まだお付き合いの段階かな？それとも兄弟姉妹かな！！わくわく。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.hato.jpg"), filename:"image.hato.jpg"), end_user_id: end_users[10].id },
    {title: 'かわいい！！', memo: 'こんなところにこんなにかわいい双子ちゃんがいるなんて！思わず写真を取らせていただいちゃいました！ありがとうございました。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.hutagozizou.jpg"), filename:"image.hutagozizou.jpg"), end_user_id: end_users[11].id },
    {title: '至福の時', memo: 'これが私の幸せのひとときなのです。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.icecoffee.jpg"), filename:"image.icecoffee.jpg"), end_user_id: end_users[11].id },
    {title: '猪やん！！', memo: 'すげー！！それだけ！！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.inoshishi.jpg"), filename:"image.inoshishi.jpg"), end_user_id: end_users[11].id },
    {title: '下を向いて歩いても', memo: '下を向いて歩こうとは言わないけど、下にも美しいものがあるのです。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.jarimichi.jpg"), filename:"image.jarimichi.jpg"), end_user_id: end_users[12].id },
    {title: 'やばい！忘れてた！', memo: 'ギリギリセーフでした～。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.kakuteishinkoku.jpg"), filename:"image.kakuteishinkoku.jpg"), end_user_id: end_users[12].id },
    {title: 'やっぱこれだね～', memo: 'これを見ると夏だな～と感じます。そして、この香り、たまらん！！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.katorisenkou.jpg"), filename:"image.katorisenkou.jpg"), end_user_id: end_users[22].id },
    {title: '直すか壊すかしてくれ！！', memo: 'って思った。絶対のどうにかするべきだけど、なんか、いい感じ。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.kuzuresou.jpg"), filename:"image.kuzuresou.jpg"), end_user_id: end_users[13].id },
    {title: 'ここに住みたい', memo: 'やばないこの景色。これを毎日見れる人が羨ましい。でも、住んでると飽きちゃうかな？', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.manshon.jpg"), filename:"image.manshon.jpg"), end_user_id: end_users[13].id },
    {title: '昭和感あふれる港', memo: 'こんな雰囲気がいい港があるのはうれしいです。港好きグループ作ろっかな？', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.minato.jpg"), filename:"image.minato.jpg"), end_user_id: end_users[13].id },
    {title: 'いい景色', memo: '最高や。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.minatomirai.jpg"), filename:"image.minatomirai.jpg"), end_user_id: end_users[13].id },
    {title: 'うまい', memo: '結局味噌汁が一番うまい説。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.misoshiru.jpg"), filename:"image.misoshiru.jpg"), end_user_id: end_users[13].id },
    {title: 'ミツバチってね', memo: '同じ花に蜜を吸いに行くらしいよ！！たぶん。てへ', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.mitsubachi.jpg"), filename:"image.mitsubachi.jpg"), end_user_id: end_users[14].id },
    {title: 'みずたまりの鏡', memo: 'みずたまりって雨が降ったあとしかないから、はなかいよな～。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.mizutamari.jpg"), filename:"image.mizutamari.jpg"), end_user_id: end_users[14].id },
    {title: '紅葉', memo: 'いい感じ。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.momiji.jpg"), filename:"image.momiji.jpg"), end_user_id: end_users[14].id },
    {title: 'ねじりんぼう', memo: 'れじりんぼう！！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.nezirinbou.jpg"), filename:"image.nezirinbou.jpg"), end_user_id: end_users[14].id },
    {title: 'このバラ素敵', memo: 'オレンジ色のバラなんてあるんですね！！素敵だったので皆さんに見てもらいたくて、投稿してみました。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.orangebara.jpg"), filename:"image.orangebara.jpg"), end_user_id: end_users[14].id },
    {title: 'PCって映える', memo: 'なんか、良くないですか？分かる人コメントで教えてね！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.pc.jpg"), filename:"image.pc.jpg"), end_user_id: end_users[14].id },
    {title: 'うますぎる', memo: '疲れたときとかに食べるラーメンが最高過ぎる。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.ramen.jpg"), filename:"image.ramen.jpg"), end_user_id: end_users[14].id },
    {title: '今日のおつまみ', memo: 'さきいか最高！！！酔ってきた～。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.sakiika.jpg"), filename:"image.sakiika.jpg"), end_user_id: end_users[15].id },
    {title: 'もうこんな時期か～', memo: '出会いと別れの季節ですね。出会いに感謝です。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.sakuranoki.jpg"), filename:"image.sakuranoki.jpg"), end_user_id: end_users[15].id },
    {title: 'うちの近所の商店街', memo: '実はもう少しでこの商店街が無くなります。新しくここにビルが建つそうです。私の大好きな場所をいつまでも忘れないように。Famoriesに残します。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.shoutengai.jpg"), filename:"image.shoutengai.jpg"), end_user_id: end_users[15].id },
    {title: 'ソバの花', memo: '初めて知った。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.sobanohana.jpg"), filename:"image.sobanohana.jpg"), end_user_id: end_users[15].id },
    {title: '水連が美しい', memo: '美しい。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.suiren.jpg"), filename:"image.suiren.jpg"), end_user_id: end_users[16].id },
    {title: '立派なタケノコです！', memo: 'これを今日は煮物にして食べました！！煮物の写真撮り忘れて食べちゃった！！泣。でもおいしかった！！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.takenoko.jpg"), filename:"image.takenoko.jpg"), end_user_id: end_users[16].id },
    {title: '友達がたくさん遊びに来てくれた。', memo: '雨なのに来てくれて本当に嬉しかった。楽しい思い出です。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.takusannokasa.jpg"), filename:"image.takusannokasa.jpg"), end_user_id: end_users[16].id },
    {title: 'うちの実家の棚田です', memo: 'ここからの景色は自分しか味わえないと思っていましたが、Famoriesで皆に共有できてうれしいです。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.tanada.jpg"), filename:"image.tanada.jpg"), end_user_id: end_users[16].id },
    {title: 'ていえん庭園ていえん', memo: 'て～～～～い～～～～え～～～～ん～～～～。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.teien.jpg"), filename:"image.teien.jpg"), end_user_id: end_users[17].id },
    {title: '都会の夜景', memo: '今日は大切な人との時間を満喫しました。ここからの景色は一生忘れません。時間も。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.tokainoyakei.jpg"), filename:"image.tokainoyakei.jpg"), end_user_id: end_users[18].id },
    {title: 'ヤギやん！！しかも２頭', memo: 'ヤギおったんですよ！！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.yagi2tou.jpg"), filename:"image.yagi2tou.jpg"), end_user_id: end_users[19].id },
    {title: 'なんかすごい砂の感じ', memo: '写真はいい感じだけど、その場にいたらめっちゃ口の中じゃりじゃりですからね！！！わら', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.yamasha.jpg"), filename:"image.yamasha.jpg"), end_user_id: end_users[20].id },
    {title: 'スキーしに行った時の写真！たしか', memo: 'ビューティフォーでしょ！', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.yukishamen.jpg"), filename:"image.yukishamen.jpg"), end_user_id: end_users[21].id },
    {title: '登山した時の景色', memo: '結構美しいかった。また行きたいとは思わないけどね。疲れたもん。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.yukiyama.jpg"), filename:"image.yukiyama.jpg"), end_user_id: end_users[21].id },
    {title: '実家に帰ってきた。', memo: 'ここが実家です。なんちゃって。', memory_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/image.zikka.jpg"), filename:"image.zikka.jpg"), end_user_id: end_users[22].id }
  ]
)

MemoryComment.create!(
  [
    {comment: 'いいね！！いいね！！', end_user_id: end_users[13].id, memory_id: memories[2].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[13].id, memory_id: memories[4].id },
    {comment: 'いいね！！グループつくりましょう！！', end_user_id: end_users[25].id, memory_id: memories[6].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[25].id, memory_id: memories[8].id },
    {comment: 'いいね！！', end_user_id: end_users[21].id, memory_id: memories[10].id },
    {comment: '素晴らしいです！！いいね！！！', end_user_id: end_users[21].id, memory_id: memories[12].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[24].id, memory_id: memories[14].id },
    {comment: 'いいね！！さいこー－－－。', end_user_id: end_users[24].id, memory_id: memories[16].id },
    {comment: 'いいね！いいね！！！', end_user_id: end_users[1].id, memory_id: memories[18].id },
    {comment: '素晴らしいです！いいね！！！！', end_user_id: end_users[1].id, memory_id: memories[20].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[22].id, memory_id: memories[22].id },
    {comment: 'さいこー－－－。いいね！！', end_user_id: end_users[22].id, memory_id: memories[24].id },
    {comment: 'いいね！！', end_user_id: end_users[3].id, memory_id: memories[26].id },
    {comment: '素晴らしいです！いいね！！！！', end_user_id: end_users[3].id, memory_id: memories[28].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[18].id, memory_id: memories[30].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[18].id, memory_id: memories[32].id },
    {comment: 'いいね！いいね！！！', end_user_id: end_users[4].id, memory_id: memories[34].id },
    {comment: '素晴らしいです！いいね！！！！', end_user_id: end_users[4].id, memory_id: memories[36].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[29].id, memory_id: memories[38].id },
    {comment: 'さいこー－－－。いいね！！', end_user_id: end_users[29].id, memory_id: memories[40].id },
    {comment: 'いいね！！いいね！！', end_user_id: end_users[22].id, memory_id: memories[42].id },
    {comment: '素晴らしいです！いいね！！！！', end_user_id: end_users[22].id, memory_id: memories[44].id },
    {comment: 'いいね！！グループつくりましょう！！', end_user_id: end_users[28].id, memory_id: memories[46].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[28].id, memory_id: memories[1].id },
    {comment: 'いいね！！', end_user_id: end_users[14].id, memory_id: memories[2].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[14].id, memory_id: memories[3].id },
    {comment: 'さいこー－－－。グループつくりましょう！！', end_user_id: end_users[5].id, memory_id: memories[4].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[5].id, memory_id: memories[5].id },
    {comment: 'いいね！さいこー－－－。！', end_user_id: end_users[15].id, memory_id: memories[6].id },
    {comment: '素晴らしいです！さいこー－－－。！！', end_user_id: end_users[15].id, memory_id: memories[7].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[15].id, memory_id: memories[8].id },
    {comment: 'さいこー－－－。さいこー－－－。', end_user_id: end_users[15].id, memory_id: memories[9].id },
    {comment: 'いいね！！', end_user_id: end_users[1].id, memory_id: memories[10].id },
    {comment: '素晴らしいです！さいこー－－－。！！', end_user_id: end_users[1].id, memory_id: memories[11].id },
    {comment: 'グループつくりましょうさいこー－－－。！！', end_user_id: end_users[16].id, memory_id: memories[12].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[16].id, memory_id: memories[13].id },
    {comment: 'いいね！さいこー－－－。！', end_user_id: end_users[2].id, memory_id: memories[14].id },
    {comment: '素晴らしいです！素晴らしいです！！！', end_user_id: end_users[2].id, memory_id: memories[15].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[2].id, memory_id: memories[16].id },
    {comment: 'さいこー－－－。素晴らしいです！', end_user_id: end_users[2].id, memory_id: memories[17].id },
    {comment: 'いいね！素晴らしいです！！', end_user_id: end_users[7].id, memory_id: memories[18].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[7].id, memory_id: memories[19].id },
    {comment: 'グループつくりましょう素晴らしいです！！！', end_user_id: end_users[24].id, memory_id: memories[20].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[24].id, memory_id: memories[21].id },
    {comment: 'いいね素晴らしいです！！！', end_user_id: end_users[19].id, memory_id: memories[22].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[19].id, memory_id: memories[23].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[1].id, memory_id: memories[24].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[1].id, memory_id: memories[25].id },
    {comment: '素晴らしいです！いいね！！', end_user_id: end_users[16].id, memory_id: memories[26].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[16].id, memory_id: memories[27].id },
    {comment: '素晴らしいです！グループつくりましょう！！', end_user_id: end_users[2].id, memory_id: memories[28].id },
    {comment: 'さいこー－－－素晴らしいです！。', end_user_id: end_users[2].id, memory_id: memories[29].id },
    {comment: 'いいね！！', end_user_id: end_users[10].id, memory_id: memories[30].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[10].id, memory_id: memories[31].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[4].id, memory_id: memories[32].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[4].id, memory_id: memories[33].id },
    {comment: 'いいね！！', end_user_id: end_users[13].id, memory_id: memories[34].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[13].id, memory_id: memories[35].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[5].id, memory_id: memories[36].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[5].id, memory_id: memories[37].id },
    {comment: 'いいね！！', end_user_id: end_users[17].id, memory_id: memories[38].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[17].id, memory_id: memories[39].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[6].id, memory_id: memories[40].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[6].id, memory_id: memories[41].id },
    {comment: 'いいね！！', end_user_id: end_users[3].id, memory_id: memories[42].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[3].id, memory_id: memories[43].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[10].id, memory_id: memories[44].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[10].id, memory_id: memories[45].id },
    {comment: 'いいね！！', end_user_id: end_users[7].id, memory_id: memories[46].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[7].id, memory_id: memories[47].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[15].id, memory_id: memories[46].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[15].id, memory_id: memories[45].id },
    {comment: 'いいね！！', end_user_id: end_users[8].id, memory_id: memories[44].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[8].id, memory_id: memories[43].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[24].id, memory_id: memories[42].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[24].id, memory_id: memories[41].id },
    {comment: 'いいね！！', end_user_id: end_users[11].id, memory_id: memories[40].id },
    {comment: '素晴らしいです！！！', end_user_id: end_users[11].id, memory_id: memories[39].id },
    {comment: 'グループつくりましょう！！', end_user_id: end_users[23].id, memory_id: memories[38].id },
    {comment: 'さいこー－－－。', end_user_id: end_users[23].id, memory_id: memories[37].id },
  ]
)

MemoryFavorite.create!(
  [
    {end_user_id: end_users[1].id, memory_id: memories[1].id},
    {end_user_id: end_users[2].id, memory_id: memories[11].id},
    {end_user_id: end_users[3].id, memory_id: memories[21].id},
    {end_user_id: end_users[4].id, memory_id: memories[31].id},
    {end_user_id: end_users[5].id, memory_id: memories[41].id},
    {end_user_id: end_users[6].id, memory_id: memories[42].id},
    {end_user_id: end_users[7].id, memory_id: memories[32].id},
    {end_user_id: end_users[8].id, memory_id: memories[22].id},
    {end_user_id: end_users[9].id, memory_id: memories[22].id},
    {end_user_id: end_users[10].id, memory_id: memories[12].id},
    {end_user_id: end_users[11].id, memory_id: memories[2].id},
    {end_user_id: end_users[12].id, memory_id: memories[3].id},
    {end_user_id: end_users[13].id, memory_id: memories[13].id},
    {end_user_id: end_users[14].id, memory_id: memories[23].id},
    {end_user_id: end_users[15].id, memory_id: memories[33].id},
    {end_user_id: end_users[16].id, memory_id: memories[43].id},
    {end_user_id: end_users[17].id, memory_id: memories[44].id},
    {end_user_id: end_users[18].id, memory_id: memories[34].id},
    {end_user_id: end_users[19].id, memory_id: memories[24].id},
    {end_user_id: end_users[21].id, memory_id: memories[14].id},
    {end_user_id: end_users[22].id, memory_id: memories[4].id},
    {end_user_id: end_users[23].id, memory_id: memories[5].id},
    {end_user_id: end_users[24].id, memory_id: memories[15].id},
    {end_user_id: end_users[25].id, memory_id: memories[25].id},
    {end_user_id: end_users[26].id, memory_id: memories[35].id},
    {end_user_id: end_users[27].id, memory_id: memories[45].id},
    {end_user_id: end_users[28].id, memory_id: memories[46].id},
    {end_user_id: end_users[29].id, memory_id: memories[36].id},
    {end_user_id: end_users[29].id, memory_id: memories[26].id},
    {end_user_id: end_users[28].id, memory_id: memories[16].id},
    {end_user_id: end_users[27].id, memory_id: memories[6].id},
    {end_user_id: end_users[26].id, memory_id: memories[7].id},
    {end_user_id: end_users[25].id, memory_id: memories[17].id},
    {end_user_id: end_users[24].id, memory_id: memories[27].id},
    {end_user_id: end_users[23].id, memory_id: memories[37].id},
    {end_user_id: end_users[22].id, memory_id: memories[47].id},
    {end_user_id: end_users[21].id, memory_id: memories[38].id},
    {end_user_id: end_users[20].id, memory_id: memories[28].id},
    {end_user_id: end_users[19].id, memory_id: memories[18].id},
    {end_user_id: end_users[18].id, memory_id: memories[8].id},
    {end_user_id: end_users[17].id, memory_id: memories[9].id},
    {end_user_id: end_users[16].id, memory_id: memories[19].id},
    {end_user_id: end_users[15].id, memory_id: memories[29].id},
    {end_user_id: end_users[14].id, memory_id: memories[39].id},
    {end_user_id: end_users[13].id, memory_id: memories[40].id},
    {end_user_id: end_users[12].id, memory_id: memories[30].id},
    {end_user_id: end_users[11].id, memory_id: memories[20].id},
    {end_user_id: end_users[10].id, memory_id: memories[10].id},
    {end_user_id: end_users[9].id, memory_id: memories[12].id},
    {end_user_id: end_users[8].id, memory_id: memories[23].id},
    {end_user_id: end_users[7].id, memory_id: memories[34].id},
    {end_user_id: end_users[6].id, memory_id: memories[45].id},
    {end_user_id: end_users[5].id, memory_id: memories[13].id},
    {end_user_id: end_users[4].id, memory_id: memories[24].id},
    {end_user_id: end_users[3].id, memory_id: memories[35].id},
    {end_user_id: end_users[2].id, memory_id: memories[46].id},
    {end_user_id: end_users[1].id, memory_id: memories[14].id},
    {end_user_id: end_users[1].id, memory_id: memories[25].id},
    {end_user_id: end_users[3].id, memory_id: memories[36].id},
    {end_user_id: end_users[5].id, memory_id: memories[47].id},
    {end_user_id: end_users[7].id, memory_id: memories[15].id},
    {end_user_id: end_users[9].id, memory_id: memories[26].id},
    {end_user_id: end_users[11].id, memory_id: memories[37].id},
    {end_user_id: end_users[13].id, memory_id: memories[16].id},
    {end_user_id: end_users[15].id, memory_id: memories[27].id},
    {end_user_id: end_users[17].id, memory_id: memories[38].id},
    {end_user_id: end_users[19].id, memory_id: memories[17].id},
    {end_user_id: end_users[21].id, memory_id: memories[28].id},
    {end_user_id: end_users[23].id, memory_id: memories[39].id},
    {end_user_id: end_users[25].id, memory_id: memories[18].id},
    {end_user_id: end_users[27].id, memory_id: memories[29].id},
    {end_user_id: end_users[29].id, memory_id: memories[19].id},
    {end_user_id: end_users[2].id, memory_id: memories[47].id},
    {end_user_id: end_users[4].id, memory_id: memories[46].id},
    {end_user_id: end_users[6].id, memory_id: memories[45].id},
    {end_user_id: end_users[8].id, memory_id: memories[44].id},
    {end_user_id: end_users[10].id, memory_id: memories[43].id},
    {end_user_id: end_users[12].id, memory_id: memories[42].id},
    {end_user_id: end_users[14].id, memory_id: memories[41].id},
    {end_user_id: end_users[15].id, memory_id: memories[40].id}
  ]
)

memory_tags = MemoryTag.create!(
  [
    {name: 'test'},
    {name: '雪'},
    {name: '風景'},
    {name: 'ヤギ'},
    {name: '都会'},
    {name: '夜景'},
    {name: '花'},
    {name: '夕暮れ'},
    {name: '田んぼ'},
    {name: '傘'},
    {name: '友達'},
    {name: '思い出'},
    {name: 'タケノコ'},
    {name: '美味しい'},
    {name: '美しい'},
    {name: '立派'},
    {name: '商店街'},
    {name: '昭和感'},
    {name: '桜'},
    {name: '春'},
    {name: '木'},
    {name: 'おつまみ'},
    {name: 'ラーメン'},
    {name: 'PC'},
    {name: '映え'},
    {name: '素敵'},
    {name: '魚'},
    {name: '紅葉'},
    {name: '水溜まり'},
    {name: 'ミツバチ'},
    {name: '味噌汁'},
    {name: '港'},
    {name: 'ビル'},
    {name: '危険'},
    {name: '階段'},
    {name: '夏'},
    {name: '懐かしい'},
    {name: '香り'},
    {name: '緊急'},
    {name: '砂利'},
    {name: '猪'},
    {name: '動物'},
    {name: '生物'},
    {name: '植物'},
    {name: 'コーヒー'},
    {name: '至福のひととき'},
    {name: '地蔵'},
    {name: 'かわいい'},
    {name: '双子'},
    {name: '鳩'},
    {name: '夫婦'},
    {name: '親子'},
    {name: '兄弟'},
    {name: '姉妹'},
    {name: '仲良し'},
    {name: '花火'},
    {name: '夏祭り'},
    {name: '祭'},
    {name: 'ギター'},
    {name: 'ガラス玉'},
    {name: 'ガムテープ'},
    {name: 'あるある'},
    {name: 'イヤホン'},
    {name: '厄介'},
    {name: '技術'},
    {name: '難しい'},
    {name: '最高'},
    {name: 'カップル'},
    {name: '乾杯'},
    {name: '中華'},
    {name: '龍'},
    {name: '絵'},
    {name: '青'},
    {name: '珍しい'},
    {name: '隙間'},
    {name: 'マンション'},
    {name: '足つぼ'},
    {name: '痛い'},
    {name: '気持い'},
    {name: '赤べこ'},
    {name: '伝統工芸'},
    {name: '山'}
  ]
)

MemorySearchTag.create!(
  [
    {memory_id: memories[1].id, memory_tag_id: memory_tags[79].id },
    {memory_id: memories[1].id, memory_tag_id: memory_tags[80].id },
    {memory_id: memories[1].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[1].id, memory_tag_id: memory_tags[71].id },
    {memory_id: memories[2].id, memory_tag_id: memory_tags[6].id },
    {memory_id: memories[2].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[2].id, memory_tag_id: memory_tags[43].id },
    {memory_id: memories[2].id, memory_tag_id: memory_tags[72].id },
    {memory_id: memories[3].id, memory_tag_id: memory_tags[76].id },
    {memory_id: memories[3].id, memory_tag_id: memory_tags[77].id },
    {memory_id: memories[3].id, memory_tag_id: memory_tags[78].id },
    {memory_id: memories[3].id, memory_tag_id: memory_tags[45].id },
    {memory_id: memories[3].id, memory_tag_id: memory_tags[64].id },
    {memory_id: memories[4].id, memory_tag_id: memory_tags[75].id },
    {memory_id: memories[4].id, memory_tag_id: memory_tags[74].id },
    {memory_id: memories[4].id, memory_tag_id: memory_tags[73].id },
    {memory_id: memories[4].id, memory_tag_id: memory_tags[34].id },
    {memory_id: memories[4].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[4].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[6].id, memory_tag_id: memory_tags[69].id },
    {memory_id: memories[6].id, memory_tag_id: memory_tags[70].id },
    {memory_id: memories[6].id, memory_tag_id: memory_tags[71].id },
    {memory_id: memories[6].id, memory_tag_id: memory_tags[15].id },
    {memory_id: memories[6].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[6].id, memory_tag_id: memory_tags[64].id },
    {memory_id: memories[7].id, memory_tag_id: memory_tags[68].id },
    {memory_id: memories[7].id, memory_tag_id: memory_tags[67].id },
    {memory_id: memories[7].id, memory_tag_id: memory_tags[66].id },
    {memory_id: memories[7].id, memory_tag_id: memory_tags[54].id },
    {memory_id: memories[7].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[7].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[7].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[7].id, memory_tag_id: memory_tags[4].id },
    {memory_id: memories[8].id, memory_tag_id: memory_tags[64].id },
    {memory_id: memories[8].id, memory_tag_id: memory_tags[65].id },
    {memory_id: memories[8].id, memory_tag_id: memory_tags[63].id },
    {memory_id: memories[8].id, memory_tag_id: memory_tags[23].id },
    {memory_id: memories[9].id, memory_tag_id: memory_tags[62].id },
    {memory_id: memories[9].id, memory_tag_id: memory_tags[73].id },
    {memory_id: memories[9].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[10].id, memory_tag_id: memory_tags[60].id },
    {memory_id: memories[10].id, memory_tag_id: memory_tags[61].id },
    {memory_id: memories[11].id, memory_tag_id: memory_tags[59].id },
    {memory_id: memories[11].id, memory_tag_id: memory_tags[72].id },
    {memory_id: memories[11].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[11].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[11].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[11].id, memory_tag_id: memory_tags[5].id },
    {memory_id: memories[11].id, memory_tag_id: memory_tags[4].id },
    {memory_id: memories[12].id, memory_tag_id: memory_tags[58].id },
    {memory_id: memories[12].id, memory_tag_id: memory_tags[64].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[55].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[56].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[57].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[35].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[13].id, memory_tag_id: memory_tags[4].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[49].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[67].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[50].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[51].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[52].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[53].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[54].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[48].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[47].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[41].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[14].id, memory_tag_id: memory_tags[10].id },
    {memory_id: memories[15].id, memory_tag_id: memory_tags[46].id },
    {memory_id: memories[15].id, memory_tag_id: memory_tags[73].id },
    {memory_id: memories[15].id, memory_tag_id: memory_tags[54].id },
    {memory_id: memories[15].id, memory_tag_id: memory_tags[48].id },
    {memory_id: memories[15].id, memory_tag_id: memory_tags[47].id },
    {memory_id: memories[15].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[16].id, memory_tag_id: memory_tags[44].id },
    {memory_id: memories[16].id, memory_tag_id: memory_tags[45].id },
    {memory_id: memories[16].id, memory_tag_id: memory_tags[68].id },
    {memory_id: memories[16].id, memory_tag_id: memory_tags[37].id },
    {memory_id: memories[16].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[16].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[16].id, memory_tag_id: memory_tags[13].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[40].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[51].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[73].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[54].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[47].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[42].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[41].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[33].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[17].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[18].id, memory_tag_id: memory_tags[39].id },
    {memory_id: memories[18].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[18].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[18].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[19].id, memory_tag_id: memory_tags[38].id },
    {memory_id: memories[19].id, memory_tag_id: memory_tags[63].id },
    {memory_id: memories[20].id, memory_tag_id: memory_tags[35].id },
    {memory_id: memories[20].id, memory_tag_id: memory_tags[36].id },
    {memory_id: memories[20].id, memory_tag_id: memory_tags[45].id },
    {memory_id: memories[20].id, memory_tag_id: memory_tags[37].id },
    {memory_id: memories[20].id, memory_tag_id: memory_tags[17].id },
    {memory_id: memories[20].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[21].id, memory_tag_id: memory_tags[33].id },
    {memory_id: memories[21].id, memory_tag_id: memory_tags[34].id },
    {memory_id: memories[21].id, memory_tag_id: memory_tags[63].id },
    {memory_id: memories[21].id, memory_tag_id: memory_tags[38].id },
    {memory_id: memories[21].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[22].id, memory_tag_id: memory_tags[32].id },
    {memory_id: memories[22].id, memory_tag_id: memory_tags[72].id },
    {memory_id: memories[22].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[22].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[22].id, memory_tag_id: memory_tags[15].id },
    {memory_id: memories[22].id, memory_tag_id: memory_tags[4].id },
    {memory_id: memories[22].id, memory_tag_id: memory_tags[5].id },
    {memory_id: memories[22].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[23].id, memory_tag_id: memory_tags[31].id },
    {memory_id: memories[23].id, memory_tag_id: memory_tags[17].id },
    {memory_id: memories[23].id, memory_tag_id: memory_tags[36].id },
    {memory_id: memories[23].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[23].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[23].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[23].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[24].id, memory_tag_id: memory_tags[32].id },
    {memory_id: memories[24].id, memory_tag_id: memory_tags[5].id },
    {memory_id: memories[24].id, memory_tag_id: memory_tags[4].id },
    {memory_id: memories[24].id, memory_tag_id: memory_tags[66].id },
    {memory_id: memories[24].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[24].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[24].id, memory_tag_id: memory_tags[13].id },
    {memory_id: memories[24].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[25].id, memory_tag_id: memory_tags[30].id },
    {memory_id: memories[25].id, memory_tag_id: memory_tags[66].id },
    {memory_id: memories[25].id, memory_tag_id: memory_tags[45].id },
    {memory_id: memories[25].id, memory_tag_id: memory_tags[36].id },
    {memory_id: memories[25].id, memory_tag_id: memory_tags[37].id },
    {memory_id: memories[25].id, memory_tag_id: memory_tags[17].id },
    {memory_id: memories[25].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[25].id, memory_tag_id: memory_tags[13].id },
    {memory_id: memories[26].id, memory_tag_id: memory_tags[29].id },
    {memory_id: memories[26].id, memory_tag_id: memory_tags[47].id },
    {memory_id: memories[26].id, memory_tag_id: memory_tags[42].id },
    {memory_id: memories[26].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[27].id, memory_tag_id: memory_tags[28].id },
    {memory_id: memories[27].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[27].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[27].id, memory_tag_id: memory_tags[39].id },
    {memory_id: memories[27].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[27].id, memory_tag_id: memory_tags[7].id },
    {memory_id: memories[28].id, memory_tag_id: memory_tags[27].id },
    {memory_id: memories[28].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[28].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[28].id, memory_tag_id: memory_tags[43].id },
    {memory_id: memories[28].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[29].id, memory_tag_id: memory_tags[26].id },
    {memory_id: memories[29].id, memory_tag_id: memory_tags[47].id },
    {memory_id: memories[29].id, memory_tag_id: memory_tags[42].id },
    {memory_id: memories[30].id, memory_tag_id: memory_tags[6].id },
    {memory_id: memories[30].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[30].id, memory_tag_id: memory_tags[15].id },
    {memory_id: memories[30].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[30].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[30].id, memory_tag_id: memory_tags[43].id },
    {memory_id: memories[30].id, memory_tag_id: memory_tags[73].id },
    {memory_id: memories[31].id, memory_tag_id: memory_tags[23].id },
    {memory_id: memories[31].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[31].id, memory_tag_id: memory_tags[64].id },
    {memory_id: memories[32].id, memory_tag_id: memory_tags[22].id },
    {memory_id: memories[32].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[32].id, memory_tag_id: memory_tags[13].id },
    {memory_id: memories[32].id, memory_tag_id: memory_tags[15].id },
    {memory_id: memories[32].id, memory_tag_id: memory_tags[37].id },
    {memory_id: memories[32].id, memory_tag_id: memory_tags[45].id },
    {memory_id: memories[33].id, memory_tag_id: memory_tags[21].id },
    {memory_id: memories[33].id, memory_tag_id: memory_tags[13].id },
    {memory_id: memories[33].id, memory_tag_id: memory_tags[45].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[18].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[20].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[6].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[15].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[19].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[34].id, memory_tag_id: memory_tags[43].id },
    {memory_id: memories[35].id, memory_tag_id: memory_tags[16].id },
    {memory_id: memories[35].id, memory_tag_id: memory_tags[17].id },
    {memory_id: memories[35].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[35].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[35].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[35].id, memory_tag_id: memory_tags[36].id },
    {memory_id: memories[36].id, memory_tag_id: memory_tags[6].id },
    {memory_id: memories[36].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[36].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[36].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[36].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[36].id, memory_tag_id: memory_tags[43].id },
    {memory_id: memories[37].id, memory_tag_id: memory_tags[6].id },
    {memory_id: memories[37].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[37].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[37].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[37].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[37].id, memory_tag_id: memory_tags[43].id },
    {memory_id: memories[38].id, memory_tag_id: memory_tags[12].id },
    {memory_id: memories[38].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[38].id, memory_tag_id: memory_tags[13].id },
    {memory_id: memories[38].id, memory_tag_id: memory_tags[15].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[9].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[10].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[17].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[36].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[47].id },
    {memory_id: memories[39].id, memory_tag_id: memory_tags[54].id },
    {memory_id: memories[40].id, memory_tag_id: memory_tags[8].id },
    {memory_id: memories[40].id, memory_tag_id: memory_tags[7].id },
    {memory_id: memories[40].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[40].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[40].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[40].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[40].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[40].id, memory_tag_id: memory_tags[36].id },
    {memory_id: memories[41].id, memory_tag_id: memory_tags[6].id },
    {memory_id: memories[41].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[41].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[41].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[41].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[5].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[4].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[32].id },
    {memory_id: memories[42].id, memory_tag_id: memory_tags[45].id },
    {memory_id: memories[43].id, memory_tag_id: memory_tags[3].id },
    {memory_id: memories[43].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[43].id, memory_tag_id: memory_tags[41].id },
    {memory_id: memories[43].id, memory_tag_id: memory_tags[47].id },
    {memory_id: memories[43].id, memory_tag_id: memory_tags[54].id },
    {memory_id: memories[44].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[44].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[44].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[44].id, memory_tag_id: memory_tags[63].id },
    {memory_id: memories[45].id, memory_tag_id: memory_tags[1].id },
    {memory_id: memories[45].id, memory_tag_id: memory_tags[81].id },
    {memory_id: memories[45].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[45].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[45].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[45].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[45].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[45].id, memory_tag_id: memory_tags[33].id },
    {memory_id: memories[46].id, memory_tag_id: memory_tags[1].id },
    {memory_id: memories[46].id, memory_tag_id: memory_tags[81].id },
    {memory_id: memories[46].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[46].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[46].id, memory_tag_id: memory_tags[14].id },
    {memory_id: memories[46].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[46].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[46].id, memory_tag_id: memory_tags[33].id },
    {memory_id: memories[47].id, memory_tag_id: memory_tags[2].id },
    {memory_id: memories[47].id, memory_tag_id: memory_tags[11].id },
    {memory_id: memories[47].id, memory_tag_id: memory_tags[24].id },
    {memory_id: memories[47].id, memory_tag_id: memory_tags[25].id },
    {memory_id: memories[47].id, memory_tag_id: memory_tags[36].id }
  ]
)